"""add phase 2 ohlcv foundation

Revision ID: 06d7ed8053ef
Revises: c4f8a19d2e7b
Create Date: 2026-08-13 16:01:29.684622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d7ed8053ef'
down_revision: Union[str, Sequence[str], None] = 'c4f8a19d2e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_import_batch',
    sa.Column('import_batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('retrieval_date', sa.DateTime(), nullable=True),
    sa.Column('trading_date_from', sa.DateTime(), nullable=True),
    sa.Column('trading_date_to', sa.DateTime(), nullable=True),
    sa.Column('rows_received', sa.Integer(), nullable=True),
    sa.Column('rows_accepted', sa.Integer(), nullable=True),
    sa.Column('rows_rejected', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('import_batch_id')
    )
    op.create_table('daily_ohlcv',
    sa.Column('daily_ohlcv_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.DateTime(), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['data_import_batch.import_batch_id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_master.stock_id'], ),
    sa.PrimaryKeyConstraint('daily_ohlcv_id'),
    sa.UniqueConstraint('stock_id', 'trading_date', 'series', name='uq_stock_date_series')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_ohlcv')
    op.drop_table('data_import_batch')
    # ### end Alembic commands ###
