"""fix_harden_fundamental_evidence_integrity

Revision ID: 520e21fa9b9b
Revises: ead94bd0c231
Create Date: 2026-08-14 13:41:44.615255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520e21fa9b9b'
down_revision: Union[str, Sequence[str], None] = 'ead94bd0c231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fundamental_metric', schema=None) as batch_op:
        batch_op.alter_column('metric_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('fundamental_snapshot', schema=None) as batch_op:
        batch_op.create_check_constraint('check_entity_type', "entity_type IN ('ORDINARY', 'BANK', 'NBFC')")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fundamental_snapshot', schema=None) as batch_op:
        batch_op.drop_constraint('check_entity_type', type_='check')

    with op.batch_alter_table('fundamental_metric', schema=None) as batch_op:
        batch_op.alter_column('metric_value',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
