"""feat_add_risk_reward_engine

Revision ID: 6291b9bcaaa3
Revises: fba661141ce8
Create Date: 2026-08-14 13:50:59.049166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6291b9bcaaa3'
down_revision: Union[str, Sequence[str], None] = 'fba661141ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_reward_result',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('support', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('resistance', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('entry_reference', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('target', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('risk_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('reward_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('risk_reward_ratio', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('config_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('config_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['candidate_evaluation_run.evaluation_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_reward_result')
    # ### end Alembic commands ###
