"""Add rich import tracking columns

Revision ID: a8c967a3411d
Revises: e7b4cc704a4d
Create Date: 2026-08-13 11:48:29.090158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c967a3411d'
down_revision: Union[str, Sequence[str], None] = 'e7b4cc704a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accepted_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejected_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duplicate_rows', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_rows', sa.Integer(), nullable=True))

    with op.batch_alter_table('import_batch_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mapped_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recommendation_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_reference_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_import_batch_detail_recommendation_id', 'broker_recommendation', ['recommendation_id'], ['recommendation_id'])
        batch_op.create_foreign_key('fk_import_batch_detail_source_reference_id', 'source_reference', ['source_reference_id'], ['source_reference_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batch_detail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_import_batch_detail_source_reference_id', type_='foreignkey')
        batch_op.drop_constraint('fk_import_batch_detail_recommendation_id', type_='foreignkey')
        batch_op.drop_column('source_reference_id')
        batch_op.drop_column('recommendation_id')
        batch_op.drop_column('action')
        batch_op.drop_column('mapped_data')
        batch_op.drop_column('raw_data')

    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.drop_column('review_rows')
        batch_op.drop_column('duplicate_rows')
        batch_op.drop_column('rejected_rows')
        batch_op.drop_column('accepted_rows')
        batch_op.drop_column('total_rows')

    # ### end Alembic commands ###
