"""feat: add corporate action evidence foundation

Revision ID: cd1603c430a0
Revises: 06d7ed8053ef
Create Date: 2026-08-14 13:10:23.867489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1603c430a0'
down_revision: Union[str, Sequence[str], None] = '06d7ed8053ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_action',
    sa.Column('corporate_action_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('ratio_numerator', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('ratio_denominator', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('cash_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action_type IN ('SPLIT', 'BONUS', 'DIVIDEND', 'RIGHTS', 'OTHER')", name='check_action_type'),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_master.stock_id'], ),
    sa.PrimaryKeyConstraint('corporate_action_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corporate_action')
    # ### end Alembic commands ###
