"""initial_schema

Revision ID: e7b4cc704a4d
Revises: 
Create Date: 2026-08-13 11:05:46.570429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b4cc704a4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_master',
    sa.Column('broker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=True),
    sa.Column('credibility_status', sa.String(length=50), nullable=True),
    sa.Column('is_historical_only', sa.Boolean(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('enabled_for_new_ingestion', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('broker_id'),
    sa.UniqueConstraint('canonical_name')
    )
    with op.batch_alter_table('broker_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broker_master_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('import_batch',
    sa.Column('batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('rating_normalization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_rating', sa.String(length=100), nullable=False),
    sa.Column('normalized_rating', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_rating')
    )
    op.create_table('source_type_master',
    sa.Column('source_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source_type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('stock_master',
    sa.Column('stock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nse_symbol', sa.String(length=50), nullable=False),
    sa.Column('bse_symbol', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap_category', sa.String(length=50), nullable=True),
    sa.Column('listing_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('isin')
    )
    with op.batch_alter_table('stock_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_master_nse_symbol'), ['nse_symbol'], unique=True)

    op.create_table('system_setting',
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('setting_key')
    )
    op.create_table('broker_alias',
    sa.Column('alias_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['broker_master.broker_id'], ),
    sa.PrimaryKeyConstraint('alias_id'),
    sa.UniqueConstraint('alias_name')
    )
    op.create_table('broker_relationship',
    sa.Column('relationship_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('predecessor_id', sa.Integer(), nullable=False),
    sa.Column('successor_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['predecessor_id'], ['broker_master.broker_id'], ),
    sa.ForeignKeyConstraint(['successor_id'], ['broker_master.broker_id'], ),
    sa.PrimaryKeyConstraint('relationship_id')
    )
    op.create_table('import_batch_detail',
    sa.Column('detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.batch_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_table('recommendation_stream',
    sa.Column('stream_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('stream_name', sa.String(length=255), nullable=False),
    sa.Column('stream_type', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('next_check_due', sa.DateTime(), nullable=True),
    sa.Column('last_successful_update', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("frequency IN ('DAILY', 'WEEKLY', 'MONTHLY', 'IRREGULAR', 'MANUAL')", name='check_frequency_allowed'),
    sa.ForeignKeyConstraint(['broker_id'], ['broker_master.broker_id'], ),
    sa.PrimaryKeyConstraint('stream_id')
    )
    op.create_table('review_queue',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('item_reference_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.batch_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('source_reference',
    sa.Column('source_reference_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type_id', sa.Integer(), nullable=False),
    sa.Column('publication_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source_date', sa.DateTime(), nullable=True),
    sa.Column('collection_timestamp', sa.DateTime(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("verification_status IN ('VERIFIED_PRIMARY', 'VERIFIED_SECONDARY', 'PROVISIONAL', 'REJECTED')", name='check_verification_status'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.batch_id'], ),
    sa.ForeignKeyConstraint(['source_type_id'], ['source_type_master.source_type_id'], ),
    sa.PrimaryKeyConstraint('source_reference_id')
    )
    op.create_table('stock_price',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_master.stock_id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_table('broker_recommendation',
    sa.Column('recommendation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_date', sa.DateTime(), nullable=False),
    sa.Column('original_rating', sa.String(length=100), nullable=False),
    sa.Column('normalized_rating', sa.String(length=100), nullable=False),
    sa.Column('recommended_price', sa.Float(), nullable=True),
    sa.Column('entry_price_low', sa.Float(), nullable=True),
    sa.Column('entry_price_high', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('time_horizon_text', sa.String(length=100), nullable=True),
    sa.Column('normalized_horizon', sa.String(length=50), nullable=True),
    sa.Column('expected_end_date', sa.DateTime(), nullable=True),
    sa.Column('analyst_name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('superseded_timestamp', sa.DateTime(), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("lifecycle_status IN ('CURRENT', 'SUPERSEDED', 'WITHDRAWN', 'HORIZON_EXPIRED', 'HISTORICAL')", name='check_lifecycle_status'),
    sa.CheckConstraint('stop_loss >= 0', name='check_stop_loss_positive'),
    sa.CheckConstraint('target_price >= 0', name='check_target_positive'),
    sa.ForeignKeyConstraint(['broker_id'], ['broker_master.broker_id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.batch_id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_master.stock_id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['recommendation_stream.stream_id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['broker_recommendation.recommendation_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_table('price_observation',
    sa.Column('observation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('observed_price', sa.Float(), nullable=False),
    sa.Column('observed_timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_reference_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.CheckConstraint('observed_price > 0', name='check_observed_price_positive'),
    sa.ForeignKeyConstraint(['source_reference_id'], ['source_reference.source_reference_id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_master.stock_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_table('recommendation_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('source_reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['broker_recommendation.recommendation_id'], ),
    sa.ForeignKeyConstraint(['source_reference_id'], ['source_reference.source_reference_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', 'source_reference_id', name='uq_rec_source')
    )
    op.create_table('recommendation_status_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['broker_recommendation.recommendation_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###

    # --- SEED DATA ---
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, Integer, Text
    
    # 1. Source Types
    source_type = table('source_type_master',
        column('type_name', String),
        column('description', Text)
    )
    op.bulk_insert(source_type, [
        {'type_name': 'BROKER_RESEARCH', 'description': 'Official broker research report'},
        {'type_name': 'BROKER_WEBSITE', 'description': 'Broker official website'},
        {'type_name': 'REPUTABLE_PUBLICATION', 'description': 'Mainstream financial news'},
        {'type_name': 'SECONDARY_WEBSITE', 'description': 'Secondary aggregator or blog'},
        {'type_name': 'AGGREGATOR', 'description': 'Data aggregator platform'}
    ])
    
    # 2. Rating Normalization
    rating_norm = table('rating_normalization',
        column('original_rating', String),
        column('normalized_rating', String)
    )
    op.bulk_insert(rating_norm, [
        {'original_rating': 'Strong Buy', 'normalized_rating': 'STRONG_BUY'},
        {'original_rating': 'Buy', 'normalized_rating': 'BUY'},
        {'original_rating': 'Accumulate', 'normalized_rating': 'ACCUMULATE'},
        {'original_rating': 'Add', 'normalized_rating': 'ADD'},
        {'original_rating': 'Outperform', 'normalized_rating': 'OUTPERFORM'},
        {'original_rating': 'Positive', 'normalized_rating': 'POSITIVE'},
        {'original_rating': 'Hold', 'normalized_rating': 'HOLD'},
        {'original_rating': 'Neutral', 'normalized_rating': 'NEUTRAL'},
        {'original_rating': 'Not Rated', 'normalized_rating': 'NOT_RATED'},
        {'original_rating': 'Reduce', 'normalized_rating': 'REDUCE'},
        {'original_rating': 'Sell', 'normalized_rating': 'SELL'},
        {'original_rating': 'Underperform', 'normalized_rating': 'UNDERPERFORM'},
    ])

    # 3. System Settings
    sys_setting = table('system_setting',
        column('setting_key', String),
        column('setting_value', String),
        column('description', Text)
    )
    op.bulk_insert(sys_setting, [
        {'setting_key': 'FRESH_MAX_DAYS', 'setting_value': '7', 'description': 'Days for FRESH bucket'},
        {'setting_key': 'RECENT_MAX_DAYS', 'setting_value': '15', 'description': 'Days for RECENT bucket'},
        {'setting_key': 'MODERATE_MAX_DAYS', 'setting_value': '30', 'description': 'Days for MODERATE bucket'},
        {'setting_key': 'STALE_MAX_DAYS', 'setting_value': '60', 'description': 'Days for STALE bucket'},
        {'setting_key': 'DEFAULT_CURRENCY', 'setting_value': 'INR', 'description': 'Default currency'},
    ])

    # 4. Broker Master Seed
    broker_master = table('broker_master',
        column('canonical_name', String),
        column('normalized_name', String),
        column('display_name', String),
        column('is_historical_only', sa.Boolean)
    )
    op.bulk_insert(broker_master, [
        {'canonical_name': 'ICICI Securities', 'normalized_name': 'icicisecurities', 'display_name': 'ICICI Direct', 'is_historical_only': False},
        {'canonical_name': 'Motilal Oswal', 'normalized_name': 'motilaloswal', 'display_name': 'Motilal Oswal', 'is_historical_only': False},
        {'canonical_name': 'HDFC Securities', 'normalized_name': 'hdfcsecurities', 'display_name': 'HDFC Securities', 'is_historical_only': False},
        {'canonical_name': 'Kotak Securities', 'normalized_name': 'kotaksecurities', 'display_name': 'Kotak Securities', 'is_historical_only': False},
        {'canonical_name': 'Axis Securities', 'normalized_name': 'axissecurities', 'display_name': 'Axis Securities', 'is_historical_only': False},
    ])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_status_history')
    op.drop_table('recommendation_source')
    op.drop_table('price_observation')
    op.drop_table('broker_recommendation')
    op.drop_table('stock_price')
    op.drop_table('source_reference')
    op.drop_table('review_queue')
    op.drop_table('recommendation_stream')
    op.drop_table('import_batch_detail')
    op.drop_table('broker_relationship')
    op.drop_table('broker_alias')
    op.drop_table('system_setting')
    with op.batch_alter_table('stock_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_master_nse_symbol'))

    op.drop_table('stock_master')
    op.drop_table('source_type_master')
    op.drop_table('rating_normalization')
    op.drop_table('import_batch')
    with op.batch_alter_table('broker_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broker_master_normalized_name'))

    op.drop_table('broker_master')
    # ### end Alembic commands ###
