"""feat_add_fundamental_evidence_models

Revision ID: ead94bd0c231
Revises: cd1603c430a0
Create Date: 2026-08-14 13:28:02.198408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead94bd0c231'
down_revision: Union[str, Sequence[str], None] = 'cd1603c430a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_snapshot',
    sa.Column('snapshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('financial_period', sa.String(length=50), nullable=True),
    sa.Column('period_type', sa.String(length=50), nullable=True),
    sa.Column('source_reference_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_reference_id'], ['source_reference.source_reference_id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_master.stock_id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['fundamental_snapshot.snapshot_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('fundamental_metric',
    sa.Column('metric_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.CheckConstraint("status IN ('KNOWN', 'UNKNOWN', 'NOT_APPLICABLE', 'STALE', 'UNSUPPORTED')", name='check_fundamental_status'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['fundamental_snapshot.snapshot_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    sa.UniqueConstraint('snapshot_id', 'metric_name', name='uq_snapshot_metric')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fundamental_metric')
    op.drop_table('fundamental_snapshot')
    # ### end Alembic commands ###
