import { useEffect, useState } from 'react';
import { settingsApi } from '../api';
import BackLink from '../components/BackLink';

const keys = ['fresh_max_days','recent_max_days','moderate_max_days','stale_max_days','universe_max_age_days'] as const;
export default function Settings() {
  const [form,setForm]=useState<any>({fresh_max_days:7,recent_max_days:15,moderate_max_days:30,stale_max_days:60,universe_max_age_days:30,eligible_normalized_ratings:'BUY,STRONG_BUY,ACCUMULATE,ADD,OUTPERFORM,POSITIVE'});
  const [message,setMessage]=useState('');
  useEffect(()=>{settingsApi.getSettings().then((rows:any[])=>{const m=Object.fromEntries(rows.map(r=>[r.setting_key,r.setting_value])); setForm((f:any)=>({...f,fresh_max_days:+(m.FRESH_MAX_DAYS??7),recent_max_days:+(m.RECENT_MAX_DAYS??15),moderate_max_days:+(m.MODERATE_MAX_DAYS??30),stale_max_days:+(m.STALE_MAX_DAYS??60),universe_max_age_days:+(m.UNIVERSE_MAX_AGE_DAYS??30),eligible_normalized_ratings:m.ELIGIBLE_BULLISH_RATINGS??f.eligible_normalized_ratings}));});},[]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setMessage('');try{await settingsApi.updateSettings({...form,eligible_normalized_ratings:form.eligible_normalized_ratings.split(',').map((x:string)=>x.trim()).filter(Boolean)});setMessage('Settings saved. Recommendation lifecycle was not changed.');}catch(err:any){setMessage(err.response?.data?.detail||'Unable to save settings');}};
  return <div className="max-w-xl mx-auto space-y-4"><BackLink fallback="/data" /><h1 className="text-2xl font-bold">Settings</h1><p className="text-sm text-gray-600">Personal Phase 1 freshness and candidate-universe configuration.</p><form onSubmit={submit} className="bg-white border rounded-lg p-4 space-y-4">{keys.map(k=><label key={k} className="block text-sm font-medium capitalize">{k.replaceAll('_',' ')}<input type="number" min="0" value={form[k]} onChange={e=>setForm({...form,[k]:+e.target.value})} className="mt-1 w-full min-h-11 border rounded p-2"/></label>)}<label className="block text-sm font-medium">Eligible normalized ratings<input value={form.eligible_normalized_ratings} onChange={e=>setForm({...form,eligible_normalized_ratings:e.target.value.toUpperCase()})} className="mt-1 w-full min-h-11 border rounded p-2"/></label><button className="w-full min-h-11 rounded bg-blue-600 text-white font-semibold">Save settings</button>{message&&<p className="text-sm break-words">{message}</p>}</form></div>;
}
